Translation "Create Your First CSS Grid".
FreeCodeCampChina/curriculum-cn pull request #12
Opened 2018-07-16 13:16 UTC by stevending1st

#### Description

 Translation "Create Your First CSS Grid".
#7 
@wudifeixue @S1ngS1ng 

#### Pre-Submission Checklist

- [x] Your pull request targets the `dev` branch.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/challenge-tests`)
- [ ] All new and existing tests pass the command `npm test`.
- [ ] Use `npm run commit` to generate a conventional commit message.
    Learn more here: <https://conventionalcommits.org/#why-use-conventional-commits>
- [x] The changes were done locally on your machine and NOT GitHub web interface.
    If they were done on the web interface you have ensured that you are creating conventional commit messages.

#### Checklist:

- [ ] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #7

2018-07-16 18:57 UTC, wudifeixue commented
收到，这次就我来详细看吧

2018-07-17 05:35 UTC, S1ngS1ng requested changes
整体上很优秀 👍
1. 记得把 `text` 里翻译好的内容粘贴到 `testString` 里面，替换 `assert` 的第二个参数
2. 检查一下前后文的一致性。比如同一个意思至少出现了如下几种翻译🤦‍♂️ ：
    - `在本行以下添加你的代码`
    - `修改本行以下的代码`
    - `更改本行下面的代码`
    - `请在本行以下输入代码`
3. 有几个注释漏掉了，加上就好

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "通过将属性 <code>display</code> 的值设为 <code>display</code>，使 HTML 元素变为网格容器。通过前面的操作，你可以对该容器使用与 CSS 网格 (CSS Grid) 相关的属性。",
这里应该是 `通过将属性 <code>display</code> 的值设为 <code>grid</code>`

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "将类名为 <code>container</code> 的 div 的 display 属性改为 <code>grid</code>。"
虽然原文没加，但这里的 `<div>` 和 `display` 外面加上 `<code></code>` 应该会比较好

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +            "assert(code.match(/.container\\s*?{[\\s\\S]*display\\s*?:\\s*?grid\\s*?;[\\s\\S]*}/gi),'<code>container</code> class should have a <code>display</code> property with a value of <code>gri
`testString` 里面定义的是测试的实例，以及测试未通过时的输出。把上面的翻译粘贴到 `assert` 的第二个参数就好。下同

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "上面的效果是使得两列各宽 50px。",
这里是个定语从句。建议：`上面的代码可以在网格容器中添加两列，宽度均为 50px`

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "在上次挑战中，你创建的网格会自动设置行数。你可以以和 <code>grid-template-columns</code> 同样的方式，使用 <code>grid-template-rows</code> 手动调整行数。",
`你可以以和 <code>grid-template-columns</code> 同样的方式，使用 <code>grid-template-rows</code> 手动调整行数。"` 建议: `你可以像用 <code>grid-template-columns</code> 设置网格的列一样，用 <code>grid-template-rows</code> 为网格设置行数。"`

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "给网格容器放置三个列，各宽 <code>100px</code>。"
`各宽 <code>100px</code>` 建议：`每列宽度均为 <code>100px</code>`

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "给网格添加两行，使每行 <code>50px</code> 高。"
~~`使每行 <code>50px</code> 高。`~~

~~建议：`使每行高度均为 <code>50px</code>。`~~

好像差别不是很大，只是个人感觉后一种说法稍微好一些。你决定吧。下同。注意保持全文一致

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "预览中的效果通过下面的代码实现：",
https://learn.freecodecamp.org/responsive-web-design/css-grid/use-css-grid-units-to-change-the-size-of-columns-and-rows/

`预览`感觉更像是直译，虽然也这样翻译没有错。不过，既然在最右边，翻译成“最右边的示例”你觉得如何？

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "这段代码创建了五个列。第一列的宽与它的内容宽度相等；第二列宽 50px ；第三列宽是它容器的 10% ；最后两列， 将剩余的宽度平均分成三份，第四列占两份，第五列占一份。",
习惯上，半角字符之后如果是全角标点，应该不需要加空格。

```
第二列宽 50px ；第三列宽是它容器的 10% ；最后两列
```
VS
```
第二列宽 50px；第三列宽是它容器的 10%；最后两列
```

@huluoyang @wudifeixue 可以加到 guideline 里？

----------

@stevending1st 不过全角逗号之后是肯定不该有空格的。去掉吧
```
最后两列， 将剩余的宽度....
        ⬆️
```

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "生成一个包含三列的网格，每列宽度如下：1fr， 100px， 和 2fr。"
这里也是一样。等一下其他人的反馈吧。

```
每列宽度如下：1fr， 100px， 和 2fr。
```
VS
```
每列宽度如下：1fr，100px，和 2fr。
```
之所以提出来这一点，一方面是翻译的 guideline 还需要添加内容。另一方面是，你在翻译中所采用 pattern 也是不统一的，比如这里 `2fr` 与后面的全角句号就没加空格，但上面的分号之前你加了空格

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "到目前为止，在你所建立的网格中列都相互紧挨着。有时候我们希望在列与列之间添加一些间隙。要在列之间添加间隙，可以使用 <code>grid-column-gap</code> 这样的属性：",
`有时候我们希望在列与列之间添加一些间隙。要在列之间添加间隙，可以使用 <code>grid-column-gap</code> 这样的属性：`

建议：

`为了在列与列之间添加一些间隙，我们可以使用 <code>grid-column-gap</code>：`

原文本身就有些许重复。既然不影响他要表达的意思，不如直接这样翻译？

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "这会在我们所有创建的列之间生成 10px 的空白间隙。",
`这会在我们所有创建的列之间生成 10px 的空白间隙。`

建议：

`这会在我们创建的所有列之间添加 10px 的空白间隙。`

--------

你翻译的肯定是没错的，只是个人觉得读起来有点儿别扭。你来决定吧

一点想法：
1. 翻译的时候要注意 it、this（当然，js 中更要注意 🌝 ）之类的指代。原文：
```
"<blockquote>grid-column-gap: 10px;</blockquote>",
"This creates 10px of empty space between all of our columns."
```
显然，这里的 `This` 指代的是上面的代码。翻译的时候，如果抽出主干部分：
```
这（这段代码）会在我们所有创建的列之间生成 10px 的空白间隙。
=>
这段代码在列之间生成空隙
```
对比：
```
这（这段代码）会为我们创建的所有列之间添加 10px 的空白间隙。
=>
这段代码在列之间添加空隙
```
感觉后者更通顺

2. 关于顺序，`我们`与`创建`构成主谓关系，关联更紧密；而`所有`与`列`是修饰关系。因此，我觉得顺序应该是`我们创建的所有列`。

3. 引申出来的一点：注意定语顺序
英语的可以参考这里：https://dictionary.cambridge.org/grammar/british-grammar/about-adjectives-and-adverbs/adjectives-order
中文只找到了这个：https://baike.baidu.com/item/%E5%A4%9A%E5%B1%82%E5%AE%9A%E8%AF%AD%E9%A1%BA%E5%BA%8F

@huluoyang @wudifeixue 如果需要，这个可以加到 guideline 里面，配合上例子会更好理解

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "给网格中的列提供 <code>20px</code> 的间隙。"
建议：
`给……提供` => `为……添加`

下面的 `创建` 同理。

前者更像是英文的直译，如 `provide`。但这样翻译不太符合中文的表达习惯

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "你可以用 <code>grid-row-gap</code> 在行与行之间添加一个间隙，就像上次挑战在列之间添加间隙一样。",
建议删掉“一个”。

英语中的不定冠词 "a" 和 "an" 不一定表示“数量 1”，也可以是虚词。
类似于中文的“在行与行之间添加 点儿/些许的 间隙”

下同

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "<code>grid-gap</code> 是 <code>grid-row-gap</code> 和 <code>grid-column-gap</code> 的简写，它更方便使用。如果 <code>grid-gap</code> 有一个值，行与行之间和列与列之间将创建等于该值的间隙。但是，如果有两个值，第一个值将作为行间隙的高度值，第二个值是列间隙的宽度值。",
`创建` 那里建议和上面一样统一一下。

其他部分翻译的很赞 👍

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "使用 <code>grid-gap</code> 在行之间引入 <code>10px</code> 的间隙，在列之间引入 <code>20px</code> 的间隙。"
`引入` 本身没有问题。但建议尽量和上面的词汇统一，这个不是大问题，你来决定就好

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "创建网格的假想水平线和垂直线被称为 <dfn> 线 (lines) </dfn>。这些线在网格的左上角从 1 开始编号，垂直线向右计，水平线向下计，累加计数。",
建议：
`垂直线向右计，水平线向下计，累加计数。` => 
`垂直线向右、水平线向下累加计数。`

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "要控制一个网格项消耗的列数，你可以将 <code>grid-column</code> 属性与你希望开始和结束的垂直线编号一起使用。",
"consume" 是消耗没有错，不过这里翻译成“网格项所占的列数”会不会更好？

--------
建议：
`要控制一个网格项消耗的列数，你可以将 <code>grid-column</code> 属性与你希望开始和结束的垂直线编号一起使用。` => 
`你可以用 <code>grid-column</code> 属性定义网格项开始和结束的位置，进而控制每个网格项所占的列数。`

或 

`如果想控制每个网格项所占的列数，你可以用 <code>grid-column</code> 属性来定义网格项开始和结束的位置。`

我个人觉得第一种比较合适，第二种更像是意译。

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "示例如下:",
请改成全角的冒号

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "这将使网格项从左侧第一条垂直线开始，跨越到第三条，消耗两列。",
建议：
`这将使网格项从左侧第一条垂直线开始，跨越到第三条，消耗两列。` => 
`这会让网格项从左侧第一条线开始到第三条线结束，占两列`

下同，不建议用“消耗”这个词

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "用值 <code>end</code> 使类为 <code>item3</code> 的网格项垂直对齐。"
这里就显然不能用“垂直对齐”对齐来表述了，因为是把 `item3` 移到下方。感觉可以说让它“靠下对齐”，或者“设置垂直对齐方式为xxx”（想不到合适的表达。。）~~或者说把它“移到下方”~~？

Before：
![image](https://user-images.githubusercontent.com/13592559/42785828-af4ea914-8908-11e8-806d-3f45ee91e4d4.png)

After：
![image](https://user-images.githubusercontent.com/13592559/42785842-b84be1ee-8908-11e8-8b53-30b2fc0a97b1.png)

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "有时你想让在 CSS 网格中的网格项共享对齐方式。你可以像之前学习的那样单独使他们对齐，也可以对网格容器使用 <code>justify-items</code> 使它们一次性水平对齐。对于这个属性你能使用在之前的两个挑战中学到的所有值，与之前不同的是，它将使网格中 <b> 所有 </b> 的网格项按所需要的方式对齐。",
建议：
`按所需要的方式对齐。` => 
`按所设置的方式对齐。`

-------

同上，这里也应该说“设置它的水平对齐方式”

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "在 CSS 网格中，每个网格项的内容分别位于被称为 <dfn> 单元格 (cell)</dfn> 的框内。你可以使用网格项的 <code>justify-self</code> 属性使其内容的位置在单元格内水平对齐。默认情况下，这个属性的值是 <code>stretch</code> ，这将使内容占满整个单元格的宽度。该 CSS 网格属性也可以使用其他的值：",
`你可以使用网格项的 <code>justify-self</code> 属性使其内容的位置在单元格内水平对齐。`
这种表达方式有点儿欠妥。应该是：
`你可以使用网格项的 <code>justify-self</code> 属性设置单元格内容水平对齐的方式`

“水平对齐“本身是一种？？？（操作？行为？想不到合适的词。。。= =），而不是一种？？？（属性？流下了表达无力的泪水）

我的理解是，你可以说”这段文字在水平方向上居中“，也可以说”这段文字的水平对齐方式是居中“，但你不能说”这段文字水平对齐“。

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "正如能使一个网格项水平对齐一样，也可以使网格项垂直对齐：你可以对网格项使用 <code>align-self</code> 属性。对于该属性，你能使用在上一个挑战中可用于 <code>justify-self</code> 属性的任一个值。",
这里一样，应该是“设置网格项的垂直对齐方式”吧。

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "对网格容器使用 <code>align-items</code> 属性可以将网格中所有网格项设置为垂直对齐。",
同上，“可以给网格中所有的网格项设置垂直对齐的方式”

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "请使用它让所有网格项移动到单元的末尾。"
上面的 `cell` 你的翻译是“单元格”。

> 在 CSS 网格中，每个网格项的内容分别位于被称为 <dfn> 单元格 (cell)</dfn> 的框内。

这里也请统一

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "你可以将网格中的一些网格单元格组合成一个 <dfn> 区域 (area) </dfn>，并为该区域指定一个自定义名称。对容器使用 <code>grid-template-areas</code> 来执行此操作：",
建议：
`对容器使用 <code>grid-template-areas</code> 来执行此操作：` => 
`你可以通过给容器加上 <code>grid-template-areas</code> 来实现：`

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "除了自定义标签，你还能使用句点（ <code>.</code> ）来描述一个空单元格",
`描述` 建议改为 `定义` 或者 `表示`

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +            "/* change code above this line */",
这里的两个注释翻译记得加上哈

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "像上一个挑战那样，在为网格容器创建区域模板后，你可以通过使用你提供的名称将网格项放入自定义区域。为此，你需要对网格项使用 <code>grid-area</code>：",
`提供` 建议改为 `定义`
`对……使用` 建议改为 `给……添加`
------

这个 “为此” 看着就很优秀了 😂

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "这使得类名为 <code>item1</code> 的网格项进入了，名为 <code>header</code> 的区域。这种情况下，网格项将使用整个顶上行，因为这一行被名为 header 区域。",
`这使得类名为 <code>item1</code> 的网格项进入了，名为 <code>header</code> 的区域`
去掉中间的逗号。。

或者：

`这样，类名为 <code>item1</code> 的网格项就被放到了名为 <code>header</code> 的区域里`

个人感觉 `lets the grid know` 可以不翻译，在英语中这样写只是为了通顺

-------

`这种情况下，网格项将使用整个顶上行，因为这一行被名为 header 区域。` =>
`此时，网格项将占满第一行，因为这一行就是 header 区域。`

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "请使用 <code>grid-area</code> 属性，让类名为 <code>item5</code> 元素放置在 <code>footer</code> 区域。"
`让……放置在` => 
`把……放到` 或 `让……位于`。推荐前者

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "你在上一次挑战中学到的 <code>grid-area</code> 属性有另一种使用方式。如果你的网格没有区域模板引用，你可以对网格项动态地创建一个区域，如：",
`如果你的网格没有区域模板引用，你可以对网格项动态地创建一个区域，如：` =>
`如果网格中没有定义区域模板，你也可以像这样为它添加一个模板：`

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "<blockquote>grid-area : 起始水平线 / 起始垂直线 / 末尾水平线 / 末尾垂直线 ;</blockquote>",
`末尾` 建议改为 `结束` 或 `终止`

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "因此，示例中的网格项将占用第 1 条和第 2 条水平线之间的行及第 1 条和第 4 条垂直线之间的列。",
~~`示例中的网格项将占用第 1 条和第 2 条水平线之间的行及第 1 条和第 4 条垂直线之间的列。` =>~~
~~`示例中的网格项将占用前 2 行及前 4 列。`~~

还是不改了吧。。。

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "请用 <code>grid-area</code> 属性将第 3 条和第 4 条水平线及第 1 条和第 4 条垂直线之间的区域放置在类名为 <code>item5</code> 的元素内。"
这里翻译的有问题。是要把 `类名为 item5` 的元素放到那个区域，而不是把那个区域放到 `item5` 里面。。

`with` 表伴随，你可能理解成 `within` 了。

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "如果要创建带 100 行相同高度的网格，单独插入 100 个值不太实际。幸运的是，有一种更好的方法——使用 <code>repeat</code> 函数指定重复的行或列的次数，后面跟逗号和需要重复的值。",
`相同高度的网格` 建议改为 `高度相同的网格`。注意语序

-------

`重复的行或列的次数` 建议改为 `行或列的重复次数`

--------

`后面跟逗号和需要重复的值。` 建议改为 `后面加上逗号以及需要重复的值`

`跟` 这个字很口语

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "你还可以用 repeat 函数重复多个值，并在定义网格结构时用该函数插入其他值。举个例子：",
`插入其他值` 个人感觉这个表示不是很好。可能说“与其他值一起使用”或者“代替部分值”会好些？你决定吧

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "<strong>注意</strong><br><code>1fr 50px</code> 重复了两次，后面跟着 20Px。",
`后面跟着 20Px。` 建议改成 `再它之后是 20px。`
注意 `px` 都是小写

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "还有一个名为 <code>minmax</code> 内置函数可用于 <code>grid-template-columns</code> 和 <code>grid-template-rows</code>。它的作用是在网格容器改变大小时限制网格项的大小。为此，你需要指定网格项可接受的尺寸范围。例如：",
第一句的语序可能要调整下：
`还有一个内置函数可用于设置 <code>grid-template-columns</code> 和 <code>grid-template-rows</code> 的值，叫做 <code>minmax</code> `
或者：
`除此之外，<code>minmax</code> 内置函数也可以可用于设置 <code>grid-template-columns</code> 和 <code>grid-template-rows</code> 的值。`

-----

`名为……内置函数` => `名为……的内置函数`

------

`网格项可接受的尺寸范围` => `网格项的尺寸范围` 或 `网格项允许的尺寸范围`

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "用 <code>minmax</code> 函数替换 <code>repeat</code> 函数中的 <code>1fr</code>，限定最小值 <code>90px</code>和最大值 <code>1fr</code>，并调整预览面板查看效果。"
`限定最小值 <code>90px</code>和最大值 <code>1fr</code>` =>
`限定其最小值为 <code>90px</code>，最大值为 <code>1fr</code>`

下一行记得也改一下

---------

`，并调整预览面板查看效果。` => 
`。你可以调整预览面板查看效果。`

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "重复函数带有一个名为 <dfn> 自动填充 (auto-fill) </dfn> 的功能。它的功能是根据容器的大小，尽可能多地自动插入预定大小的行或宽。你能将 <code>auto-fill</code> 和 <code>minmax</code> 组合，以便灵活地布局。",
感觉这里的 `<code>repeat</code> function` 翻译成 `<code>repeat</code> 方法` 可能会更好吧。。。“重复函数” 有点儿奇怪。

------

`尽可能多地自动插入预定大小的行或宽` => `尽可能多地放入指定大小的行或列`

------

`你能将 <code>auto-fill</code> 和 <code>minmax</code> 组合，以便灵活地布局。` => 
`你可以通过结合 <code>auto-fill</code> 和 <code>minmax</code> 来更灵活地布局`

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "上面的代码效果：当容器大小改变，将继续拉伸列，直至可以插入一个满足要求（至少 60px 宽）的列。（译者注:动手试试你将更明白）",
`当容器大小改变，将继续拉伸列，直至可以插入一个满足要求（至少 60px 宽）的列。` =>
`列的宽度会随容器大小改变，直到直至可以插入一个 60px 宽的列之前，当前行的所有列会一直拉伸`

----------

`译者注:` 很优秀。不过这里应该是全角冒号`：`

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "在第一个网格中，用 <code>auto-fill</code> 和 <code>repeat</code> 来填充网格，其中列宽的最小值为 <code>60px</code>，最大值为 <code>1fr</code>。并调整预览面板大小，查看自动填充效果。"
同上，`你可以调整……`。下同

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +            "<code>container</code> 类应该有 <code>grid-template-columns</code> 属性且使用 <code>repeat</code> 和 <code>auto-fill</code>，以便于最小宽度为 <code>60px</code>，最大宽度为 <code>1fr</code> 的列填充网格。",
`以便于最小宽度为 <code>60px</code>，最大宽度为 <code>1fr</code> 的列填充网格。` => 
`以便将最小宽度为 <code>60px</code>，最大宽度为 <code>1fr</code> 的列填充至网格。`

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "<code>auto-fit</code> 效果几乎和 <code>auto-fill</code> 一样。不同点仅在于，当容器的大小大于各网格项之和时，<code>auto-fill</code> 将一直插入空行或空列，使所有网格项紧靠一边；而 <code>auto-fit</code> 将不会插入空行或空列，使所有网格项拉伸至合适的大小。",
`<code>auto-fill</code> 将一直插入空行或空列，使所有网格项紧靠一边` =>
`<code>auto-fill</code> 将会持续地在一端插入空行或空列，这样就会把所有网格项挤到另一边`

---------

`而 <code>auto-fit</code> 将不会插入空行或空列，使所有网格项拉伸至合适的大小。` =>
`而 <code>auto-fit</code> 则不会在一端插入空行或空列，而是将所有网格项拉伸至合适的大小。`

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +            "<code>container2</code> 类应该有 <code>grid-template-columns</code> 属性，且使用 <code>repeat</code> 和 <code>auto-fit</code> 以便最小宽度为 <code>60px</code>，最大宽度为 <code>1fr</code> 的列插入网格。",
改法见上一道题。

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "在预览中，当网页可视区域的宽不小于 300px 时，列数从 1 变为 2。并且，广告 (advertisement) 区域完全全占据左列。",
多了个 `全`

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "将元素转换为网格只会影响其子代元素。因此，在将一个子代元素转换为网格，将会使一个网格嵌套一个网格。",
原文是 `direct descendants`，代表的意思是类似与 css 里面的 `>` selector。翻译成 `子代元素` 好像没问题。。
查了下 MDN 也是这么叫的 https://developer.mozilla.org/zh-CN/docs/Web/CSS/Child_selectors。。另一种叫后代选择器

不过总怕闹误会= =

--------

`因此，在将一个子代元素转换为网格，将会使一个网格嵌套一个网格。` =>
`因此，如果把子代设置为网格，将会得到一个嵌套的网格。`

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "例如，设置类名为 <code>item3</code> 的元素的 <code>display</code> 和 <code>grid-template-columns</code> 属性，在网格中创建一个网格。",
`在网格中创建一个网格` => 
`就会得到一个嵌套的网格`

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +            "<code>item3</code> class should have a <code>display</code> property with the value of <code>grid</code>.",
这里也要翻译下哈。

2018-07-17 05:35 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +            "<code>item3</code> 类应该有 <code>grid-template-columns</code> 属性且将 <code>auto</code> 和 <code>1fr</code> 作为值。",
`且将 <code>auto</code> 和 <code>1fr</code> 作为值。` => 
`且值为 <code>auto</code> 和 <code>1fr</code>。`

2018-07-18 11:44 UTC, huluoyang commented
@stevending1st  抱歉，我们新开了 challenges 仓库来专门做翻译，此仓库不再用作翻译。

详情请传送到：https://github.com/freecodecampchina/challenges

2018-07-20 12:32 UTC, stevending1st commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "将元素转换为网格只会影响其子代元素。因此，在将一个子代元素转换为网格，将会使一个网格嵌套一个网格。",
`因此，在将某个子代元素设置为网格，将会得到一个嵌套的网格。`

2018-07-20 13:40 UTC, stevending1st commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "<code>auto-fit</code> 效果几乎和 <code>auto-fill</code> 一样。不同点仅在于，当容器的大小大于各网格项之和时，<code>auto-fill</code> 将一直插入空行或空列，使所有网格项紧靠一边；而 <code>auto-fit</code> 将不会插入空行或空列，使所有网格项拉伸至合适的大小。",
`<code>auto-fill</code> 将会持续地在一端插入空行或空列，这样就会使所有网格项挤到另一边；`

<hr>

`而 <code>auto-fit</code> 则不会在一端插入空行或空列，而是会将所有网格项拉伸至合适的大小。`

2018-07-20 13:52 UTC, stevending1st commented on challenges/01-responsive-web-design/css-grid-cn.json
> +            "<code>container2</code> 类应该有 <code>grid-template-columns</code> 属性，且使用 <code>repeat</code> 和 <code>auto-fit</code> 以便最小宽度为 <code>60px</code>，最大宽度为 <code>1fr</code> 的列插入网格。",
`且使用 <code>repeat</code> 和 <code>auto-fit</code> 以便将最小宽度为 <code>60px</code>，最大宽度为 <code>1fr</code> 的列插入网格。`

2018-07-20 16:24 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "将元素转换为网格只会影响其子代元素。因此，在将一个子代元素转换为网格，将会使一个网格嵌套一个网格。",
@stevending1st 感觉还是有点儿重复，换成 “把” 可能好些。
而且读起来不是很顺，缺少连接词：
`因此，在把某个子代元素设置为网格后，就会得到一个嵌套的网格。`

2018-07-21 07:01 UTC, stevending1st commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "预览中的效果通过下面的代码实现：",
“最右边的预览区域”？

2018-07-21 08:07 UTC, stevending1st commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "到目前为止，在你所建立的网格中列都相互紧挨着。有时候我们希望在列与列之间添加一些间隙。要在列之间添加间隙，可以使用 <code>grid-column-gap</code> 这样的属性：",
`如果要在列与列之间添加一些间隙，我们可以使用 <code>grid-column-gap</code>：`

2018-07-21 12:45 UTC, stevending1st commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "你可以用 <code>grid-row-gap</code> 在行与行之间添加一个间隙，就像上次挑战在列之间添加间隙一样。",
```
"和上个挑战在两列之间添加间隙一样，你可以用 <code>grid-row-gap</code> 在两行之间添加间隙，。",
"<hr>",
"在两行行之间添加高度为 <code>5px</code> 的间隙。"
```

2018-07-21 12:46 UTC, stevending1st commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "给网格中的列提供 <code>20px</code> 的间隙。"
`为网格中的列添加 <code>20px</code> 的间隙。`

2018-07-21 13:05 UTC, stevending1st commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "<code>grid-gap</code> 是 <code>grid-row-gap</code> 和 <code>grid-column-gap</code> 的简写，它更方便使用。如果 <code>grid-gap</code> 有一个值，行与行之间和列与列之间将创建等于该值的间隙。但是，如果有两个值，第一个值将作为行间隙的高度值，第二个值是列间隙的宽度值。",
`如果 <code>grid-gap</code> 有一个值，行与行之间和列与列之间将添加等于该值的间隙。`

2018-07-21 13:10 UTC, stevending1st commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "使用 <code>grid-gap</code> 在行之间引入 <code>10px</code> 的间隙，在列之间引入 <code>20px</code> 的间隙。"
`使用 <code>grid-gap</code> 在行之间【添加】 <code>10px</code> 的间隙，在列之间【添加】 <code>20px</code> 的间隙。`

2018-07-21 13:34 UTC, stevending1st commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "要控制一个网格项消耗的列数，你可以将 <code>grid-column</code> 属性与你希望开始和结束的垂直线编号一起使用。",
`你可以用 <code>grid-column</code> 属性定义网格项开始和结束的位置，进而控制每个网格项【占用】的列数。`

2018-07-21 13:40 UTC, stevending1st commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "这将使网格项从左侧第一条垂直线开始，跨越到第三条，消耗两列。",
```
"这会让网格项从左侧第一条线开始到第三条线结束，【占用】两列。",
"<hr>",
"使类为 <code>item5</code> 的网格项【占用】网格的最后两列。"
```

2018-07-21 14:30 UTC, stevending1st commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "用值 <code>end</code> 使类为 <code>item3</code> 的网格项垂直对齐。"
借用PPT里的术语“底端对齐”。
<hr>

`正如能使一个网格项水平对齐一样，也可以使网格项【底端对齐】`

<hr>

`用值 <code>end</code> 使类为 <code>item3</code> 的网格项【底端对齐】。`

2018-07-21 20:29 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "预览中的效果通过下面的代码实现：",
@stevending1st 嗯。感觉好些

2018-07-24 02:01 UTC, stevending1st commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "用值 <code>end</code> 使类为 <code>item3</code> 的网格项垂直对齐。"
`align an item horizontally` =>`沿行轴对齐`;
`align an item vertically`=>`沿列轴对齐`.
@S1ngS1ng

2018-07-24 02:10 UTC, stevending1st commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "这使得类名为 <code>item1</code> 的网格项进入了，名为 <code>header</code> 的区域。这种情况下，网格项将使用整个顶上行，因为这一行被名为 header 区域。",
`这样，类名为 <code>item1</code> 的网格项就被放到了 <code>header</code> 区域里。`

<hr>

`这种情况下，网格项将使用整个顶上行，因为这一行被名为 header 区域。`

2018-07-24 03:14 UTC, stevending1st commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "请用 <code>grid-area</code> 属性将第 3 条和第 4 条水平线及第 1 条和第 4 条垂直线之间的区域放置在类名为 <code>item5</code> 的元素内。"
`请用 <code>grid-area</code> 属性将类为 <code>item5</code> 的元素放置在第 3 条和第 4 条水平线及第 1 条和第 4 条垂直线之间的区域内。`

2018-07-24 06:16 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "用值 <code>end</code> 使类为 <code>item3</code> 的网格项垂直对齐。"
@stevending1st 好的，没问题

2018-07-24 08:35 UTC, stevending1st commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "还有一个名为 <code>minmax</code> 内置函数可用于 <code>grid-template-columns</code> 和 <code>grid-template-rows</code>。它的作用是在网格容器改变大小时限制网格项的大小。为此，你需要指定网格项可接受的尺寸范围。例如：",
`除此之外，内置函数 <code>minmax</code> 也可以可用于设置 <code>grid-template-columns</code> 和 <code>grid-template-rows</code> 的值。`

<hr>

`你需要指定网格项的尺寸范围。`

2018-07-24 10:25 UTC, stevending1st commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "上面的代码效果：当容器大小改变，将继续拉伸列，直至可以插入一个满足要求（至少 60px 宽）的列。（译者注:动手试试你将更明白）",
`列的宽度会随容器大小改变，在可以插入一个 60px 宽的列之前，当前行的所有列会一直拉伸。`

2018-07-24 11:03 UTC, stevending1st commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "正如能使一个网格项水平对齐一样，也可以使网格项垂直对齐：你可以对网格项使用 <code>align-self</code> 属性。对于该属性，你能使用在上一个挑战中可用于 <code>justify-self</code> 属性的任一个值。",
`正如能设置网格项沿行轴对齐方式一样，也可以设置网格项沿列轴对齐方式：`

2018-07-24 11:06 UTC, stevending1st commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "在 CSS 网格中，每个网格项的内容分别位于被称为 <dfn> 单元格 (cell)</dfn> 的框内。你可以使用网格项的 <code>justify-self</code> 属性使其内容的位置在单元格内水平对齐。默认情况下，这个属性的值是 <code>stretch</code> ，这将使内容占满整个单元格的宽度。该 CSS 网格属性也可以使用其他的值：",
`你可以使用网格项的 <code>justify-self</code> 属性设置其内容的位置在单元格内沿行轴对齐的方式。`

2018-07-24 11:11 UTC, stevending1st commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "对网格容器使用 <code>align-items</code> 属性可以将网格中所有网格项设置为垂直对齐。",
`可以给网格中所有的网格项设置沿列轴对齐的方式。`

2018-07-24 17:00 UTC, S1ngS1ng commented on challenges/01-responsive-web-design/css-grid-cn.json
> +        "上面的代码效果：当容器大小改变，将继续拉伸列，直至可以插入一个满足要求（至少 60px 宽）的列。（译者注:动手试试你将更明白）",
@stevending1st 可以的

2018-07-29 05:57 UTC, S1ngS1ng commented
Addressed in FreeCodeCampChina/challenges#30

2018-07-29 05:57 UTC, closed without merging